/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityLogEntry {
  'oldValue' : string,
  'user' : string,
  'newValue' : string,
  'timestamp' : Time,
  'fieldName' : string,
}
export interface ClientProfile {
  'id' : bigint,
  'tin' : string,
  'placeOfBirth' : string,
  'status' : ClientStatus,
  'onboardingDate' : [] | [Time],
  'accountId' : string,
  'clientType' : ClientType,
  'dateOfBirth' : string,
  'createdBy' : Principal,
  'createdDate' : Time,
  'passportExpiryDate' : string,
  'kycHistory' : Array<KYCEntry>,
  'nationality' : string,
  'email' : string,
  'activityLog' : Array<string>,
  'kycReviewDue' : [] | [Time],
  'relationshipManager' : Principal,
  'address' : string,
  'riskJustification' : string,
  'phone' : string,
  'passportNumber' : string,
  'primaryCountry' : string,
  'lastName' : string,
  'riskLevel' : RiskLevel,
  'onboardingSteps' : Array<OnboardingStep>,
  'firstName' : string,
}
export type ClientStatus = { 'active' : null } |
  { 'prospect' : null } |
  { 'onboarding' : null } |
  { 'offboarded' : null };
export type ClientType = { 'entity' : null } |
  { 'individual' : null };
export interface DashboardStats {
  'prospectCount' : bigint,
  'lowRiskCount' : bigint,
  'offboardedCount' : bigint,
  'mediumRiskCount' : bigint,
  'highRiskCount' : bigint,
  'totalClients' : bigint,
  'activeCount' : bigint,
  'onboardingCount' : bigint,
}
export interface KYCEntry { 'result' : string, 'date' : Time, 'notes' : string }
export interface OnboardingCard {
  'clientId' : bigint,
  'clientName' : string,
  'dueDate' : [] | [Time],
  'stepNumber' : bigint,
  'assignedPerson' : string,
  'stepStatus' : string,
}
export interface OnboardingStage {
  'cards' : Array<OnboardingCard>,
  'stageName' : string,
}
export interface OnboardingStep {
  'status' : string,
  'completionDate' : [] | [Time],
  'completed' : boolean,
  'dueDate' : [] | [Time],
  'description' : string,
  'stepNumber' : bigint,
  'assignedPerson' : string,
}
export interface OverviewFieldUpdate {
  'tin' : [] | [string],
  'placeOfBirth' : [] | [string],
  'dateOfBirth' : [] | [string],
  'passportExpiryDate' : [] | [string],
  'nationality' : [] | [string],
  'email' : [] | [string],
  'address' : [] | [string],
  'phone' : [] | [string],
  'passportNumber' : [] | [string],
  'primaryCountry' : [] | [string],
  'lastName' : [] | [string],
  'firstName' : [] | [string],
}
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'appendActivityLogEntries' : ActorMethod<
    [bigint, Array<ActivityLogEntry>],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClient' : ActorMethod<[ClientProfile], bigint>,
  'deleteClient' : ActorMethod<[bigint], undefined>,
  'getAllClients' : ActorMethod<[], Array<ClientProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClient' : ActorMethod<[bigint], ClientProfile>,
  'getClientActivityLog' : ActorMethod<[bigint], Array<string>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getOnboardingPipeline' : ActorMethod<[], Array<OnboardingStage>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'moveClientToStage' : ActorMethod<
    [bigint, bigint, string, string, [] | [Time]],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateClient' : ActorMethod<[bigint, ClientProfile], undefined>,
  'updateClientOverviewFields' : ActorMethod<
    [bigint, OverviewFieldUpdate],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];