/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AdminRole = IDL.Variant({
  'operator' : IDL.Null,
  'staff' : IDL.Null,
});
export const Time = IDL.Int;
export const ActivityLogEntry = IDL.Record({
  'oldValue' : IDL.Text,
  'user' : IDL.Text,
  'newValue' : IDL.Text,
  'timestamp' : Time,
  'fieldName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClientStatus = IDL.Variant({
  'active' : IDL.Null,
  'prospect' : IDL.Null,
  'onboarding' : IDL.Null,
  'offboarded' : IDL.Null,
});
export const ClientType = IDL.Variant({
  'entity' : IDL.Null,
  'individual' : IDL.Null,
});
export const KYCEntry = IDL.Record({
  'result' : IDL.Text,
  'date' : Time,
  'notes' : IDL.Text,
});
export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const OnboardingStep = IDL.Record({
  'status' : IDL.Text,
  'completionDate' : IDL.Opt(Time),
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(Time),
  'description' : IDL.Text,
  'stepNumber' : IDL.Nat,
  'assignedPerson' : IDL.Text,
});
export const ClientProfile = IDL.Record({
  'id' : IDL.Nat,
  'tin' : IDL.Text,
  'placeOfBirth' : IDL.Text,
  'status' : ClientStatus,
  'onboardingDate' : IDL.Opt(Time),
  'accountId' : IDL.Text,
  'clientType' : ClientType,
  'dateOfBirth' : IDL.Text,
  'createdBy' : IDL.Principal,
  'createdDate' : Time,
  'passportExpiryDate' : IDL.Text,
  'kycHistory' : IDL.Vec(KYCEntry),
  'nationality' : IDL.Text,
  'email' : IDL.Text,
  'activityLog' : IDL.Vec(IDL.Text),
  'kycReviewDue' : IDL.Opt(Time),
  'relationshipManager' : IDL.Principal,
  'address' : IDL.Text,
  'riskJustification' : IDL.Text,
  'phone' : IDL.Text,
  'passportNumber' : IDL.Text,
  'primaryCountry' : IDL.Text,
  'lastName' : IDL.Text,
  'riskLevel' : RiskLevel,
  'onboardingSteps' : IDL.Vec(OnboardingStep),
  'firstName' : IDL.Text,
});
export const AdminEntry = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'role' : AdminRole,
  'addedOn' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'prospectCount' : IDL.Nat,
  'lowRiskCount' : IDL.Nat,
  'offboardedCount' : IDL.Nat,
  'mediumRiskCount' : IDL.Nat,
  'highRiskCount' : IDL.Nat,
  'totalClients' : IDL.Nat,
  'activeCount' : IDL.Nat,
  'onboardingCount' : IDL.Nat,
});
export const OnboardingCard = IDL.Record({
  'clientId' : IDL.Nat,
  'clientName' : IDL.Text,
  'dueDate' : IDL.Opt(Time),
  'stepNumber' : IDL.Nat,
  'assignedPerson' : IDL.Text,
  'stepStatus' : IDL.Text,
});
export const OnboardingStage = IDL.Record({
  'cards' : IDL.Vec(OnboardingCard),
  'stageName' : IDL.Text,
});
export const AuthorizationStatus = IDL.Variant({
  'authorized' : IDL.Null,
  'operatorMissing' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const AuthorizationResult = IDL.Record({
  'status' : AuthorizationStatus,
  'message' : IDL.Text,
});
export const OverviewFieldUpdate = IDL.Record({
  'tin' : IDL.Opt(IDL.Text),
  'placeOfBirth' : IDL.Opt(IDL.Text),
  'dateOfBirth' : IDL.Opt(IDL.Text),
  'passportExpiryDate' : IDL.Opt(IDL.Text),
  'nationality' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
  'passportNumber' : IDL.Opt(IDL.Text),
  'primaryCountry' : IDL.Opt(IDL.Text),
  'lastName' : IDL.Opt(IDL.Text),
  'firstName' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAdmin' : IDL.Func([IDL.Principal, IDL.Text, AdminRole], [IDL.Bool], []),
  'appendActivityLogEntries' : IDL.Func(
      [IDL.Nat, IDL.Vec(ActivityLogEntry)],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClient' : IDL.Func([ClientProfile], [IDL.Nat], []),
  'deleteClient' : IDL.Func([IDL.Nat], [], []),
  'getAdminEntries' : IDL.Func([], [IDL.Vec(AdminEntry)], ['query']),
  'getAdminEntry' : IDL.Func([IDL.Principal], [AdminEntry], ['query']),
  'getAllClients' : IDL.Func([], [IDL.Vec(ClientProfile)], ['query']),
  'getAllowlistSize' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerAdminEntry' : IDL.Func([], [IDL.Opt(AdminEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClient' : IDL.Func([IDL.Nat], [ClientProfile], ['query']),
  'getClientActivityLog' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getOnboardingPipeline' : IDL.Func([], [IDL.Vec(OnboardingStage)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAuthorized' : IDL.Func([], [AuthorizationResult], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'moveClientToStage' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(Time)],
      [],
      [],
    ),
  'removeAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateClient' : IDL.Func([IDL.Nat, ClientProfile], [], []),
  'updateClientOverviewFields' : IDL.Func(
      [IDL.Nat, OverviewFieldUpdate],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AdminRole = IDL.Variant({ 'operator' : IDL.Null, 'staff' : IDL.Null });
  const Time = IDL.Int;
  const ActivityLogEntry = IDL.Record({
    'oldValue' : IDL.Text,
    'user' : IDL.Text,
    'newValue' : IDL.Text,
    'timestamp' : Time,
    'fieldName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClientStatus = IDL.Variant({
    'active' : IDL.Null,
    'prospect' : IDL.Null,
    'onboarding' : IDL.Null,
    'offboarded' : IDL.Null,
  });
  const ClientType = IDL.Variant({
    'entity' : IDL.Null,
    'individual' : IDL.Null,
  });
  const KYCEntry = IDL.Record({
    'result' : IDL.Text,
    'date' : Time,
    'notes' : IDL.Text,
  });
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const OnboardingStep = IDL.Record({
    'status' : IDL.Text,
    'completionDate' : IDL.Opt(Time),
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(Time),
    'description' : IDL.Text,
    'stepNumber' : IDL.Nat,
    'assignedPerson' : IDL.Text,
  });
  const ClientProfile = IDL.Record({
    'id' : IDL.Nat,
    'tin' : IDL.Text,
    'placeOfBirth' : IDL.Text,
    'status' : ClientStatus,
    'onboardingDate' : IDL.Opt(Time),
    'accountId' : IDL.Text,
    'clientType' : ClientType,
    'dateOfBirth' : IDL.Text,
    'createdBy' : IDL.Principal,
    'createdDate' : Time,
    'passportExpiryDate' : IDL.Text,
    'kycHistory' : IDL.Vec(KYCEntry),
    'nationality' : IDL.Text,
    'email' : IDL.Text,
    'activityLog' : IDL.Vec(IDL.Text),
    'kycReviewDue' : IDL.Opt(Time),
    'relationshipManager' : IDL.Principal,
    'address' : IDL.Text,
    'riskJustification' : IDL.Text,
    'phone' : IDL.Text,
    'passportNumber' : IDL.Text,
    'primaryCountry' : IDL.Text,
    'lastName' : IDL.Text,
    'riskLevel' : RiskLevel,
    'onboardingSteps' : IDL.Vec(OnboardingStep),
    'firstName' : IDL.Text,
  });
  const AdminEntry = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'role' : AdminRole,
    'addedOn' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'prospectCount' : IDL.Nat,
    'lowRiskCount' : IDL.Nat,
    'offboardedCount' : IDL.Nat,
    'mediumRiskCount' : IDL.Nat,
    'highRiskCount' : IDL.Nat,
    'totalClients' : IDL.Nat,
    'activeCount' : IDL.Nat,
    'onboardingCount' : IDL.Nat,
  });
  const OnboardingCard = IDL.Record({
    'clientId' : IDL.Nat,
    'clientName' : IDL.Text,
    'dueDate' : IDL.Opt(Time),
    'stepNumber' : IDL.Nat,
    'assignedPerson' : IDL.Text,
    'stepStatus' : IDL.Text,
  });
  const OnboardingStage = IDL.Record({
    'cards' : IDL.Vec(OnboardingCard),
    'stageName' : IDL.Text,
  });
  const AuthorizationStatus = IDL.Variant({
    'authorized' : IDL.Null,
    'operatorMissing' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const AuthorizationResult = IDL.Record({
    'status' : AuthorizationStatus,
    'message' : IDL.Text,
  });
  const OverviewFieldUpdate = IDL.Record({
    'tin' : IDL.Opt(IDL.Text),
    'placeOfBirth' : IDL.Opt(IDL.Text),
    'dateOfBirth' : IDL.Opt(IDL.Text),
    'passportExpiryDate' : IDL.Opt(IDL.Text),
    'nationality' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
    'passportNumber' : IDL.Opt(IDL.Text),
    'primaryCountry' : IDL.Opt(IDL.Text),
    'lastName' : IDL.Opt(IDL.Text),
    'firstName' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAdmin' : IDL.Func([IDL.Principal, IDL.Text, AdminRole], [IDL.Bool], []),
    'appendActivityLogEntries' : IDL.Func(
        [IDL.Nat, IDL.Vec(ActivityLogEntry)],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClient' : IDL.Func([ClientProfile], [IDL.Nat], []),
    'deleteClient' : IDL.Func([IDL.Nat], [], []),
    'getAdminEntries' : IDL.Func([], [IDL.Vec(AdminEntry)], ['query']),
    'getAdminEntry' : IDL.Func([IDL.Principal], [AdminEntry], ['query']),
    'getAllClients' : IDL.Func([], [IDL.Vec(ClientProfile)], ['query']),
    'getAllowlistSize' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerAdminEntry' : IDL.Func([], [IDL.Opt(AdminEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClient' : IDL.Func([IDL.Nat], [ClientProfile], ['query']),
    'getClientActivityLog' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getOnboardingPipeline' : IDL.Func(
        [],
        [IDL.Vec(OnboardingStage)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAuthorized' : IDL.Func([], [AuthorizationResult], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'moveClientToStage' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(Time)],
        [],
        [],
      ),
    'removeAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateClient' : IDL.Func([IDL.Nat, ClientProfile], [], []),
    'updateClientOverviewFields' : IDL.Func(
        [IDL.Nat, OverviewFieldUpdate],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };