/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface KYCEntry {
    result: string;
    date: Time;
    notes: string;
}
export type Time = bigint;
export interface OnboardingCard {
    clientId: bigint;
    clientName: string;
    dueDate?: Time;
    stepNumber: bigint;
    assignedPerson: string;
    stepStatus: string;
}
export interface ClientProfile {
    id: bigint;
    dob?: string;
    status: ClientStatus;
    onboardingDate?: Time;
    clientType: ClientType;
    name: string;
    createdBy: Principal;
    createdDate: Time;
    kycHistory: Array<KYCEntry>;
    nationality: string;
    email: string;
    activityLog: Array<string>;
    kycReviewDue?: Time;
    relationshipManager: Principal;
    address: string;
    riskJustification: string;
    phone: string;
    riskLevel: RiskLevel;
    onboardingSteps: Array<OnboardingStep>;
}
export interface OnboardingStage {
    cards: Array<OnboardingCard>;
    stageName: string;
}
export interface OnboardingStep {
    status: string;
    completionDate?: Time;
    completed: boolean;
    dueDate?: Time;
    description: string;
    stepNumber: bigint;
    assignedPerson: string;
}
export interface DashboardStats {
    prospectCount: bigint;
    lowRiskCount: bigint;
    offboardedCount: bigint;
    mediumRiskCount: bigint;
    highRiskCount: bigint;
    totalClients: bigint;
    activeCount: bigint;
    onboardingCount: bigint;
}
export interface UserProfile {
    name: string;
    role: string;
    email: string;
}
export enum ClientStatus {
    active = "active",
    prospect = "prospect",
    onboarding = "onboarding",
    offboarded = "offboarded"
}
export enum ClientType {
    entity = "entity",
    individual = "individual"
}
export enum RiskLevel {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createClient(profile: ClientProfile): Promise<bigint>;
    deleteClient(id: bigint): Promise<void>;
    getAllClients(): Promise<Array<ClientProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClient(id: bigint): Promise<ClientProfile>;
    getDashboardStats(): Promise<DashboardStats>;
    getOnboardingPipeline(): Promise<Array<OnboardingStage>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    moveClientToStage(clientId: bigint, stepNumber: bigint, status: string, assignedPerson: string, dueDate: Time | null): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateClient(id: bigint, updatedProfile: ClientProfile): Promise<void>;
}
import type { ClientProfile as _ClientProfile, ClientStatus as _ClientStatus, ClientType as _ClientType, KYCEntry as _KYCEntry, OnboardingCard as _OnboardingCard, OnboardingStage as _OnboardingStage, OnboardingStep as _OnboardingStep, RiskLevel as _RiskLevel, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createClient(arg0: ClientProfile): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createClient(to_candid_ClientProfile_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClient(to_candid_ClientProfile_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteClient(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async getAllClients(): Promise<Array<ClientProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClients();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClients();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClient(arg0: bigint): Promise<ClientProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getClient(arg0);
                return from_candid_ClientProfile_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClient(arg0);
            return from_candid_ClientProfile_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getOnboardingPipeline(): Promise<Array<OnboardingStage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOnboardingPipeline();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOnboardingPipeline();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async moveClientToStage(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: Time | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.moveClientToStage(arg0, arg1, arg2, arg3, to_candid_opt_n37(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moveClientToStage(arg0, arg1, arg2, arg3, to_candid_opt_n37(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateClient(arg0: bigint, arg1: ClientProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0, to_candid_ClientProfile_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0, to_candid_ClientProfile_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ClientProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClientProfile): ClientProfile {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ClientStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClientStatus): ClientStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ClientType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClientType): ClientType {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_OnboardingCard_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OnboardingCard): OnboardingCard {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_OnboardingStage_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OnboardingStage): OnboardingStage {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_OnboardingStep_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OnboardingStep): OnboardingStep {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    dob: [] | [string];
    status: _ClientStatus;
    onboardingDate: [] | [_Time];
    clientType: _ClientType;
    name: string;
    createdBy: Principal;
    createdDate: _Time;
    kycHistory: Array<_KYCEntry>;
    nationality: string;
    email: string;
    activityLog: Array<string>;
    kycReviewDue: [] | [_Time];
    relationshipManager: Principal;
    address: string;
    riskJustification: string;
    phone: string;
    riskLevel: _RiskLevel;
    onboardingSteps: Array<_OnboardingStep>;
}): {
    id: bigint;
    dob?: string;
    status: ClientStatus;
    onboardingDate?: Time;
    clientType: ClientType;
    name: string;
    createdBy: Principal;
    createdDate: Time;
    kycHistory: Array<KYCEntry>;
    nationality: string;
    email: string;
    activityLog: Array<string>;
    kycReviewDue?: Time;
    relationshipManager: Principal;
    address: string;
    riskJustification: string;
    phone: string;
    riskLevel: RiskLevel;
    onboardingSteps: Array<OnboardingStep>;
} {
    return {
        id: value.id,
        dob: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.dob)),
        status: from_candid_ClientStatus_n18(_uploadFile, _downloadFile, value.status),
        onboardingDate: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.onboardingDate)),
        clientType: from_candid_ClientType_n21(_uploadFile, _downloadFile, value.clientType),
        name: value.name,
        createdBy: value.createdBy,
        createdDate: value.createdDate,
        kycHistory: value.kycHistory,
        nationality: value.nationality,
        email: value.email,
        activityLog: value.activityLog,
        kycReviewDue: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.kycReviewDue)),
        relationshipManager: value.relationshipManager,
        address: value.address,
        riskJustification: value.riskJustification,
        phone: value.phone,
        riskLevel: from_candid_RiskLevel_n23(_uploadFile, _downloadFile, value.riskLevel),
        onboardingSteps: from_candid_vec_n25(_uploadFile, _downloadFile, value.onboardingSteps)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    completionDate: [] | [_Time];
    completed: boolean;
    dueDate: [] | [_Time];
    description: string;
    stepNumber: bigint;
    assignedPerson: string;
}): {
    status: string;
    completionDate?: Time;
    completed: boolean;
    dueDate?: Time;
    description: string;
    stepNumber: bigint;
    assignedPerson: string;
} {
    return {
        status: value.status,
        completionDate: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.completionDate)),
        completed: value.completed,
        dueDate: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.dueDate)),
        description: value.description,
        stepNumber: value.stepNumber,
        assignedPerson: value.assignedPerson
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cards: Array<_OnboardingCard>;
    stageName: string;
}): {
    cards: Array<OnboardingCard>;
    stageName: string;
} {
    return {
        cards: from_candid_vec_n34(_uploadFile, _downloadFile, value.cards),
        stageName: value.stageName
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clientId: bigint;
    clientName: string;
    dueDate: [] | [_Time];
    stepNumber: bigint;
    assignedPerson: string;
    stepStatus: string;
}): {
    clientId: bigint;
    clientName: string;
    dueDate?: Time;
    stepNumber: bigint;
    assignedPerson: string;
    stepStatus: string;
} {
    return {
        clientId: value.clientId,
        clientName: value.clientName,
        dueDate: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.dueDate)),
        stepNumber: value.stepNumber,
        assignedPerson: value.assignedPerson,
        stepStatus: value.stepStatus
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    prospect: null;
} | {
    onboarding: null;
} | {
    offboarded: null;
}): ClientStatus {
    return "active" in value ? ClientStatus.active : "prospect" in value ? ClientStatus.prospect : "onboarding" in value ? ClientStatus.onboarding : "offboarded" in value ? ClientStatus.offboarded : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entity: null;
} | {
    individual: null;
}): ClientType {
    return "entity" in value ? ClientType.entity : "individual" in value ? ClientType.individual : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): RiskLevel {
    return "low" in value ? RiskLevel.low : "high" in value ? RiskLevel.high : "medium" in value ? RiskLevel.medium : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClientProfile>): Array<ClientProfile> {
    return value.map((x)=>from_candid_ClientProfile_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OnboardingStep>): Array<OnboardingStep> {
    return value.map((x)=>from_candid_OnboardingStep_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OnboardingStage>): Array<OnboardingStage> {
    return value.map((x)=>from_candid_OnboardingStage_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OnboardingCard>): Array<OnboardingCard> {
    return value.map((x)=>from_candid_OnboardingCard_n35(_uploadFile, _downloadFile, x));
}
function to_candid_ClientProfile_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClientProfile): _ClientProfile {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ClientStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClientStatus): _ClientStatus {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ClientType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClientType): _ClientType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_OnboardingStep_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OnboardingStep): _OnboardingStep {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_RiskLevel_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): _RiskLevel {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    completionDate?: Time;
    completed: boolean;
    dueDate?: Time;
    description: string;
    stepNumber: bigint;
    assignedPerson: string;
}): {
    status: string;
    completionDate: [] | [_Time];
    completed: boolean;
    dueDate: [] | [_Time];
    description: string;
    stepNumber: bigint;
    assignedPerson: string;
} {
    return {
        status: value.status,
        completionDate: value.completionDate ? candid_some(value.completionDate) : candid_none(),
        completed: value.completed,
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        description: value.description,
        stepNumber: value.stepNumber,
        assignedPerson: value.assignedPerson
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    dob?: string;
    status: ClientStatus;
    onboardingDate?: Time;
    clientType: ClientType;
    name: string;
    createdBy: Principal;
    createdDate: Time;
    kycHistory: Array<KYCEntry>;
    nationality: string;
    email: string;
    activityLog: Array<string>;
    kycReviewDue?: Time;
    relationshipManager: Principal;
    address: string;
    riskJustification: string;
    phone: string;
    riskLevel: RiskLevel;
    onboardingSteps: Array<OnboardingStep>;
}): {
    id: bigint;
    dob: [] | [string];
    status: _ClientStatus;
    onboardingDate: [] | [_Time];
    clientType: _ClientType;
    name: string;
    createdBy: Principal;
    createdDate: _Time;
    kycHistory: Array<_KYCEntry>;
    nationality: string;
    email: string;
    activityLog: Array<string>;
    kycReviewDue: [] | [_Time];
    relationshipManager: Principal;
    address: string;
    riskJustification: string;
    phone: string;
    riskLevel: _RiskLevel;
    onboardingSteps: Array<_OnboardingStep>;
} {
    return {
        id: value.id,
        dob: value.dob ? candid_some(value.dob) : candid_none(),
        status: to_candid_ClientStatus_n5(_uploadFile, _downloadFile, value.status),
        onboardingDate: value.onboardingDate ? candid_some(value.onboardingDate) : candid_none(),
        clientType: to_candid_ClientType_n7(_uploadFile, _downloadFile, value.clientType),
        name: value.name,
        createdBy: value.createdBy,
        createdDate: value.createdDate,
        kycHistory: value.kycHistory,
        nationality: value.nationality,
        email: value.email,
        activityLog: value.activityLog,
        kycReviewDue: value.kycReviewDue ? candid_some(value.kycReviewDue) : candid_none(),
        relationshipManager: value.relationshipManager,
        address: value.address,
        riskJustification: value.riskJustification,
        phone: value.phone,
        riskLevel: to_candid_RiskLevel_n9(_uploadFile, _downloadFile, value.riskLevel),
        onboardingSteps: to_candid_vec_n11(_uploadFile, _downloadFile, value.onboardingSteps)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == RiskLevel.low ? {
        low: null
    } : value == RiskLevel.high ? {
        high: null
    } : value == RiskLevel.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClientStatus): {
    active: null;
} | {
    prospect: null;
} | {
    onboarding: null;
} | {
    offboarded: null;
} {
    return value == ClientStatus.active ? {
        active: null
    } : value == ClientStatus.prospect ? {
        prospect: null
    } : value == ClientStatus.onboarding ? {
        onboarding: null
    } : value == ClientStatus.offboarded ? {
        offboarded: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClientType): {
    entity: null;
} | {
    individual: null;
} {
    return value == ClientType.entity ? {
        entity: null
    } : value == ClientType.individual ? {
        individual: null
    } : value;
}
function to_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<OnboardingStep>): Array<_OnboardingStep> {
    return value.map((x)=>to_candid_OnboardingStep_n12(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
